# Generated by Django 3.1.4 on 2020-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_number', models.CharField(max_length=255)),
                ('account_branch', models.CharField(max_length=255)),
                ('account_branch_ifsc', models.CharField(max_length=255)),
                ('account_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debited_from', models.CharField(max_length=255)),
                ('credited_to', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(default='PENDING', max_length=255)),
            ],
        ),
    ]
