# Generated by Django 3.1.4 on 2020-12-02 12:25

import core.models.customers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=core.models.customers.get_customer_id, max_length=255, primary_key=True, serialize=False),
        ),
    ]
