# Generated by Django 3.1.4 on 2020-12-02 12:42

import core.models.customers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201202_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=core.models.customers.get_customer_id, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
