# Generated by Django 3.1.4 on 2020-12-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201202_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=1, upload_to='static/assets/uploads/customer_images/'),
            preserve_default=False,
        ),
    ]
